name: jio_provider
description: Simple light weight provider inherited widget, basic, multi, eager and lazy jio providers.
version: 1.0.0
repository: https://github.com/jiocoders/jio_provider_flutter
issue_tracker: https://github.com/jiocoders/jio_provider_flutter/issues
homepage: https://github.com/jiocoders/jio_provider_flutter
documentation: https://jiocoders.com
topics: [ state-management, jio-provider, multi-jio-provider, eager-jio-provider, lazy-jio-provider ]
funding: [ https://jiocoders.com ]

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
screenshots:
  - description: The jio provider package logo.
    path: screenshots/provider.jpeg